Complete remove and status functionality

diff --git a/legit-add b/legit-add
--- a/legit-add
+++ b/legit-add
@@ -3,14 +3,14 @@
 # Test if repo initiated
 if [ ! -d '.legit' ]
 then
-    echo "legit-add: error: no .legit directory containing legit repository exists"
+    echo "legit-add: error: no .legit directory containing legit repository exists" 1>&2
     exit 1
 fi
 
 # Test if usage correct
 if [ $# -lt 1 ]
 then
-    echo "usage: legit-add <filenames>"
+    echo "usage: legit-add <filenames>" 1>&2
     exit 1
 fi
 
@@ -18,28 +18,38 @@ fi
 for file in $@
 do
     # Check for invalid filename
-    if echo "$file" | egrep -v "[A-Za-z0-9._-]"
+    if echo "$file" | egrep -v "[A-Za-z0-9._-]" >/dev/null
     then
-        echo "legit-add: error: invalid filename '$file'"
+        echo "legit-add: error: invalid filename '$file'" 1>&2
         exit 1
     fi
 
     if [ -d "$file" ]
     then
-        echo "legit-add: error: '$file' is not a regular file"
+        echo "legit-add: error: '$file' is not a regular file" 1>&2
         exit 1
     fi
 
-    if [ ! -f "$file" ]
+    if [ ! -e "$file" ]
     then
         # TODO: check if file is just deleted from previous commit
-        echo "legit-add: error: can not open '$file'"
+        if egrep " $file$" '.legit/index' >/dev/null
+        then
+            continue
+        fi
+        echo "legit-add: error: can not open '$file'" 1>&2
         exit 1
     fi
 done
 
 for file in $@
 do
+    if [ ! -e "$file" ]
+    then
+        # Stage file deletion
+        sed -i "/ $file$/d" '.legit/index'
+        continue
+    fi
 
     size=`ls -l "$file" | cut -d' ' -f4`
     content=`cat "$file"`
@@ -48,11 +58,18 @@ do
 
     if [ ! -f ".legit/objects/$sha" ]
     then
+        # Store file content to objects folder
         cp "$file" ".legit/objects/$sha"
-        egrep -v " $file$" '.legit/index' >'.legit/indextmp'
-        mv '.legit/indextmp' '.legit/index'
+        # Remove previous staging
+        sed -i "/ $file$/d" '.legit/index'
+        # Add file to index staging area
         echo "blob $sha $file" >>'.legit/index'
-        #cat '.legit/index'
+        # cat '.legit/index'
+    elif ! egrep "^blob $sha $file$" '.legit/index' >/dev/null
+    then
+        # Remove previous staging
+        sed -i "/ $file$/d" '.legit/index'
+        echo "blob $sha $file" >>'.legit/index'
     fi
 done
 exit 0
diff --git a/legit-commit b/legit-commit
--- a/legit-commit
+++ b/legit-commit
@@ -8,14 +8,14 @@
 # Test if no repo
 if [ ! -d '.legit' ]
 then
-    echo "legit-commit: error: no .legit directory containing legit repository exists"
+    echo "legit-commit: error: no .legit directory containing legit repository exists" 1>&2
     exit 1
 fi
 
 
 if [ ! $# -eq 2 ] && [ ! $# -eq 3 ]
 then
-    echo 'usage: legit-commit [-a] -m commit-message'
+    echo 'usage: legit-commit [-a] -m commit-message' 1>&2
     exit 1
 fi
 
@@ -28,7 +28,7 @@ elif [ "$1" = '-m' ] && [ "$#" -eq 2 ]
 then
     m=1
 else
-    echo 'usage: legit-commit [-a] -m commit-message'
+    echo 'usage: legit-commit [-a] -m commit-message' 1>&2
     exit 1
 fi
 
@@ -37,13 +37,13 @@ then
     mess="$3"
     if [ "$2" = '-a' ]
     then
-        echo 'usage: legit-commit [-a] -m commit-message'
+        echo 'usage: legit-commit [-a] -m commit-message' 1>&2
         exit 1
     elif [ $m -eq 0 ] && [ "$2" = '-m' ]
     then
         m=1
     else
-        echo 'usage: legit-commit [-a] -m commit-message'
+        echo 'usage: legit-commit [-a] -m commit-message' 1>&2
         exit 1
     fi
 else
@@ -56,20 +56,20 @@ fi
 if [ "$a" = 1 ]
 then
     # TODO:Change file name when running autotest
-    ./legit-status >".legit/commitstatus" 2>&1
+    legit-status >".legit/commitstatus" 2>&1
     while read -r line
     do
         name=`echo $line | cut -d' ' -f1`
         stat=`echo $line | cut -d' ' -f3-`
         if echo "$stat" | egrep "changes not staged for commit" >/dev/null
         then
-            ./legit-add "$name"
+            legit-add "$name"
         elif echo "$stat" | egrep "different changes staged for commit" >/dev/null
         then
-            ./legit-add "$name"
+            legit-add "$name"
         elif echo "$stat" | egrep "file deleted" >/dev/null
         then
-            ./legit-add "$name"
+            legit-add "$name"
         fi
         
     done <'.legit/commitstatus'
@@ -78,7 +78,7 @@ fi
 
 
 # Check if anything to commit
-./legit-status >".legit/commitstatus" 2>&1
+legit-status >".legit/commitstatus" 2>&1
 if [ $? -ne 0 ]
 then
     rm ".legit/commitstatus"
@@ -93,7 +93,8 @@ else
     toCommit=0
     while read -r line
     do
-        stat=`echo $line | cut -d' ' -f3-`
+        stat=`echo "$line" | cut -d' ' -f3-`
+        name=`echo "$line" | cut -d' ' -f1`
         if echo "$stat" | egrep "added to index" >/dev/null
         then
             toCommit=1
@@ -102,15 +103,25 @@ else
         then
             toCommit=1
             break
-        elif echo "$stat" | egrep "file deleted" >/dev/null
+        elif echo "$stat" | egrep "^deleted$" >/dev/null
         then
             toCommit=1
             break
+        elif echo "$stat" | egrep "^untracked$" >/dev/null
+        then
+            branch=`cat '.legit/HEAD'`
+            rc=`cat ".legit/$branch"`
+            # recent commit object is at .legit/objects/$rc
+            if egrep " $name$" ".legit/objects/$rc" >/dev/null
+            then
+                # if object that exist in previous commit is now untracked
+                toCommit=1
+                break
+            fi
         fi
     done <'.legit/commitstatus'
     rm '.legit/commitstatus'
-
-    if [ $toCommit -eq 0 ]
+    if [ "$toCommit" -eq 0 ]
     then
         echo "nothing to commit"
         exit 0
diff --git a/legit-init b/legit-init
--- a/legit-init
+++ b/legit-init
@@ -2,7 +2,7 @@
 
 if test -d '.legit'
 then
-    echo "legit-init: error: .legit already exists"
+    echo "legit-init: error: .legit already exists" 1>&2
     exit 1
 fi
 
diff --git a/legit-log b/legit-log
--- a/legit-log
+++ b/legit-log
@@ -3,13 +3,13 @@
 # Test if no repo
 if [ ! -d '.legit' ]
 then
-    echo "legit-log: error: no .legit directory containing legit repository exists"
+    echo "legit-log: error: no .legit directory containing legit repository exists" 1>&2
     exit 1
 fi
 
 if [ ! -f '.legit/log' ]
 then
-    echo "legit-log: error: your repository does not have any commits yet"
+    echo "legit-log: error: your repository does not have any commits yet" 1>&2
     exit 1
 fi
 
diff --git a/legit-rm b/legit-rm
--- a/legit-rm
+++ b/legit-rm
@@ -2,4 +2,116 @@
 
 # Legit rm implementation
 
+if [ ! -d '.legit' ]
+then
+    echo "legit-rm: error: no .legit directory containing legit repository exists" 1>&2
+    exit 1
+fi
+
+if [ ! -f '.legit/log' ]
+then
+    echo "legit-rm: error: your repository does not have any commits yet" 1>&2
+    exit 1
+fi
+
+if [ $# -eq 0 ]
+then
+    echo "usage: legit-rm [--force] [--cached] <filenames>" 1>&2
+    exit 1
+fi
+
+cached=0
+forced=0
+if [ $1 = '--cached' ]
+then
+    cached=1
+    sta=2
+    if [ $2 = '--force' ]
+    then
+        forced=1
+        sta=3
+    fi
+elif [ $1 = '--force' ]
+then
+    forced=1
+    sta=2
+    if [ $2 = '--cached' ]
+    then
+        cached=1
+        sta=3
+    fi
+else
+    sta=1
+fi
+
+
+if [ ! $# -ge $sta ]
+then
+    echo "usage: legit-rm [--force] [--cached] <filenames>" 1>&2
+    exit 1
+fi
+
+# Check all remaining arguments are valid
+files=`echo $@ | cut -d' ' -f$sta-`
+for arg in $files
+do
+    if ! egrep " $arg$" '.legit/index' >/dev/null
+    then
+        echo "legit-rm: error: '$arg' is not in the legit repository" 1>&2
+        exit 1
+    fi
+done
+
+if [ $forced = '0' ] # && [ $cached = '0' ]
+then
+    # Set path to recent commit of HEAD
+    branch=`cat '.legit/HEAD'`
+    rc=`cat ".legit/$branch"`
+    rcPath="objects/$rc"
+    
+    # check for changes
+    for arg in $files
+    do
+        # Get recent commit sha of this file
+        blobRc=`egrep " $arg$" ".legit/$rcPath"`
+        rcSha=`echo "$blobRc" | cut -d' ' -f2`
+        # Get file sha in index    
+        indexLine=`egrep " $arg$" ".legit/index"`
+        indSha=`echo "$indexLine" | cut -d' ' -f2`
+        if [ -f $arg ]
+        then
+            # if file exist in working directory
+            # Compute working directory file sha hash
+            size=`ls -l "$arg" | cut -d' ' -f4`
+            content=`cat "$arg"`
+            wdSha=`echo "blob$size$content" | sha1sum | egrep -o '[^ -]*'`
+        fi
+        # echo "rc $rcSha"
+        # echo "wd $wdSha"
+        # echo "index $indSha"
+        if [ "$rcSha" != "$indSha" ] && [ "$wdSha" != "$indSha" ]
+        then
+            echo "legit-rm: error: '$arg' in index is different to both working file and repository" 1>&2
+            exit 1
+        elif [ "$rcSha" != "$indSha" ] && [ "$cached" = '0' ]
+        then
+            echo "legit-rm: error: '$arg' has changes staged in the index" 1>&2
+            exit 1
+        elif [ "$wdSha" != "$rcSha" ] && [ "$cached" = '0' ]
+        then
+            echo "legit-rm: error: '$arg' in repository is different to working file" 1>&2
+            exit 1
+        fi
+        
+    done
+fi
+
+for arg in $files
+do
+    sed -i "/ $arg$/d" '.legit/index'
+    if [ $cached = '0' ]
+    then
+        rm "$arg" >/dev/null 2>&1
+    fi
+done
 
diff --git a/legit-status b/legit-status
--- a/legit-status
+++ b/legit-status
@@ -5,7 +5,7 @@
 # check for commits
 if [ ! -f '.legit/commit' ]
 then
-    echo "legit-status: error: your repository does not have any commits yet"
+    echo "legit-status: error: your repository does not have any commits yet" 1>&2
     exit 1
 fi
 
@@ -44,35 +44,38 @@ do
         content=`cat "$file"`
         wdSha=`echo "blob$size$content" | sha1sum | egrep -o '[^ -]*'`
         rcSha=`echo "$blobRc" | cut -d' ' -f2`
+        # Get index hash
+        indexLine=`egrep " $file$" ".legit/index"`
+        indSha=`echo "$indexLine" | cut -d' ' -f2`
 
-        # Check if working directory hash is same as recent commit hash
-        # To see if changes were made
-        if echo "$wdSha" | egrep "^$rcSha$" >/dev/null
+        # Check if index hash is same as recent commit hash
+        # To see if changes were staged
+        if echo "$indSha" | egrep "^$rcSha$" >/dev/null
         then
-            # same as repo
-            echo "$file - same as repo" >>'.legit/status'
-        else
-            # Check if file name exist in index
-            # To see if changes staged
-            indexLine=`egrep " $file$" ".legit/index"`
-            indSha=`echo "$indexLine" | cut -d' ' -f2`
-            
-            # Check if index hash is same as repo hash
-            if echo "$indSha" | egrep "^$rcSha$" >/dev/null
+            if echo "$wdSha" | egrep "^$rcSha$" >/dev/null
             then
+                # same as repo
+                echo "$file - same as repo" >>'.legit/status'
+            else
                 # changes are not staged for commit
                 echo "$file - file changed, changes not staged for commit" >>'.legit/status'
+            fi
+        else
+            # there are changes staged
+            # Check if working directory hash is same as index hash
+            if echo "$wdSha" | egrep "^$indSha$" >/dev/null
+            then
+                # same as index sha
+                echo "$file - file changed, changes staged for commit" >>'.legit/status'
             else
-                # there are changes staged
-                # Check if working directory hash is same as index hash
-                if echo "$wdSha" | egrep "^$indSha$" >/dev/null
+                if [ -z "$indSha" ]
                 then
-                    # same as index sha
-                    echo "$file - file changed, changes staged for commit" >>'.legit/status'
-                else
-                    # different to index sha
-                    echo "$file - file changed, different changes staged for commit" >>'.legit/status'
+                    # file not in index, but was in recent commit
+                    echo "$file - untracked" >>'.legit/status'
+                    continue
                 fi
+                # different to index sha
+                echo "$file - file changed, different changes staged for commit" >>'.legit/status'
             fi
         fi
     fi
@@ -83,17 +86,15 @@ echo "$files" |
 while read -r line
 do
     name=`echo "$line" | cut -d' ' -f3-`
-    if [ -f "$name" ]
+    if [ -f "$name" ] || [ -z "$name" ]
     then
         # file still exists in directory
         continue
     fi
-
     # Check if filename exist in index
-    indexLine=`egrep " $name$" ".legit/index"`
-    echo $indexLine
-    if [ ! -z "$indexLine" ]
+    if egrep " $name$" ".legit/index" >/dev/null
     then
+        indexLine=`egrep " $name$" ".legit/index"`
         blobRc=`egrep " $name$" ".legit/$rcPath"`
         rcSha=`echo "$blobRc" | cut -d' ' -f2`
         indSha=`echo "$indexLine" | cut -d' ' -f2`
@@ -102,19 +103,18 @@ do
         then
             # file deleted
             # same as index sha, not yet staged
-            echo "$file - file deleted" >>'.legit/status'
+            echo "$name - file deleted" >>'.legit/status'
         else
             # file deleted, different changes staged for commit
             # different to index sha
-            echo "$file - file deleted, different changes staged for commit" >>'.legit/status'
-        fi        
+            echo "$name - file deleted, different changes staged for commit" >>'.legit/status'
+        fi       
     else
-        # deleted
         # File no longer in both working directory and index
-        echo "$file - deleted" >>'.legit/status'
+        echo "$name - deleted" >>'.legit/status'
     fi
 done
 
 
-cat '.legit/status' | sort
+sort '.legit/status'
 rm '.legit/status'
